package org.lotka.xenonx.domain.util

object Constants {

    const val POLY_LINE: String = "POLY_LINE"
    const val TR: String = "tr"
    const val EN: String = "en"

    const val VERSION_CODE: Int = 1069
    const val COMPANY_DOCUMENT_FILE_SIZE: Float = 10f
    const val ANDROID: String = "ANDROID"
    const val NO_HAS_FCM_TOKEN: String = "notHasFcmToken"
    const val WORK_EXPERIENCE_ADDED: String = "WORK_EXPERIENCE_ADDED"

    const val FILTER: String = "FILTER"
    const val EXCHANGE_FILTER_STATUS: String = "EXCHANGE_FILTER_STATUS"
    const val OPEN_PROFILE: String = "OPEN_PROFILE"
    const val OPEN_MY_ADS: String = "OPEN_MY_ADS"
    const val AUTHORIZATION: String = "authorization"
    const val Accept_Language: String = "Accept-Language"
    const val Connection: String = "Connection"
    const val STAV = "stav"
    const val Message = "Message"
    const val LANGUAGE: String = "language"
    const val FCM: String = "FCM"
    const val STORE: String = "STORE"
    const val CATEGORY: String = "CATEGORY"
    const val SOFTWARE: String = "SOFTWARE"
    const val FIREBASE_TOKEN: String = "FIREBASE_TOKEN"
    const val TOKEN = "token"
    const val EXCHANGE_ALERT = "EXCHANGE_ALERT"
    const val EXCHANGE_ANIMATION = "EXCHANGE_ANIMATION"
    const val CHANGE_LANGUAGE = "CHANGE_LANGUAGE"
    const val GUEST_TOKEN = "guest_token"
    const val SERVER_URL = "SERVER_URL"
    const val MESSAGING_SOCKET = "MESSAGING_SOCKET"
    const val SERVER_SCHEME = "SERVER_SCHEME"
    const val ROUTES: String = "routes"
    const val ACCESS_TOKEN_EXPIRE_TIME: String = "access_token_expire_time"
    const val ACCESS_TOKEN = "access_token"
    const val REFRESH_TOKEN = "refresh_token"
    const val CHANGE_PROFILE = "navigation"
    const val FCM_TOKEN = "fcm_token"


    const val EMPTY = "empty"
    const val FIRST_NAME = "first_name"
    const val LAST_NAME = "last_name"
    const val USER_TYPE = "user_type"
    const val GUEST_USER_TYPE = "quest_user_type"
    const val TAG = "BuluroApplication"
    const val SelectedLocation = "SelectedLocation"
    const val Chats = "Chats"
    const val COUNTRY = "COUNTRY"
    const val MON = "MON"
    const val TUE = "TUE"
    const val WED = "WED"
    const val THU = "THU"
    const val FRI = "FRI"
    const val SAT = "SAT"
    const val SUN = "SUN"
    const val All = "ALL"
    const val EMPLOYEE = "EMPLOYEE"
    const val EMPLOYER = "EMPLOYER"


    const val BRANCH = "BRANCH"
    const val SECTION = "SECTION"
    const val COMPANY_SIZE = "COMPANY_SIZE"
    const val COMPANY = "COMPANY"
    const val UNIVERSITY = "UNIVERSITY"
    const val GRADE = "GRADE"
    const val LANGUAGE_LEVEL = "LANGUAGE_LEVEL"
    const val SCHOOL_LEVEL = "SCHOOL_LEVEL"
    const val UNIVERSITY_NAME = "UNIVERSITY_NAME"
    const val COMPANY_NAME = "COMPANY_NAME"
    const val DONT_FIND_COMPANY = "DONT_FIND_COMPANY"
    const val CITY = "CITY"
    const val TOWN = "TOWN"
    const val NEIGHBORHOOD = "NEIGHBORHOOD"
    const val COUNTY = "COUNTY"
    const val CITY_COUNTY = "CITY_COUNTY"
    const val LOCATION_FILTER = "LOCATION_FILTER"
    const val COME_FROM = "COME_FROM"
    const val COME_FROM_HOME = "COME_FROM_HOME"
    const val SELECTED_CITY = "SELECTED_CITY"
    const val SELECTED_COUNTIES = "SELECTED_COUNTIES"
    const val ADDRESS_ADDED = "ADDRESS_ADDED"

    const val DRAFT = "DRAFT"
    const val ACTIVE = "ACTIVE"
    const val DE_ACTIVE = "DE_ACTIVE"

    const val BOOST = "BOOST"
    const val ARCHIVED = "ARCHIVE"
    const val EXPIRED = "EXPIRED"
    const val ADMIN_BAN = "ADMIN_BAN"

    const val LOCATION = "LOCATION"

    const val EMPLOYEE_DEFAULT_LOCATION = "EMPLOYEE_DEFAULT_LOCATION"
    const val EMPLOYEE_SELECTED_LOCATION = "EMPLOYEE_SELECTED_LOCATION"
    const val POSTER_STATUS = "POSTER_STATUS"
    const val NOTIFICATION_STATUS = "NOTIFICATION_STATUS"
    const val NOTIFICATION_DATA = "NOTIFICATION_DATA"
    const val PAGE_SIZE = 50
    const val EXCHANGE_SOCKET = "EXCHANGE_SOCKET"
    const val MESSAGE_SOCKET = "MESSAGE_SOCKET"

    const val UNIQUE_ID = "UNIQUE_ID"
    const val UNIQUE_ID_HEADER = "uniqueid"
    const val DELETE_ACCOUNT_REASON = "DELETE_ACCOUNT_REASON"

    //Flavors
    const val TEST_ENVIRONMENT = "uat"
    const val DEVELOPMENT_ENVIRONMENT = "development"
    const val PRODUCTION_ENVIRONMENT = "production"
    const val ENVIRONMENT = "ENVIRONMENT"

    const val RUN_SPLASH = "RUN_SPLASH"

    const val FLOOR = "FLOOR"
    const val ROOM = "ROOM"
    const val BUILDING_AGE = "BUILDING_AGE"
    const val HEATING = "HEATING"
}